android {
    signingConfigs {
        release {
            storeFile file("path/to/my-release-key.jks")
            storePassword "yourStorePassword"
            keyAlias "my-key-alias"
            keyPassword "yourKeyPassword"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false  // Use Proguard if needed
            shrinkResources false
        }
    }
}
